# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<dmilitaru@fastly.com>"]
description = "Make your own word game, using Fastly's Compute@Edge 🦀"
language = "rust"
manifest_version = 3
name = "yourdle"
service_id = "IV46ATG54AR2sdPXjQ9NG6"

[local_server]

  [local_server.backends]

  [local_server.kv_stores]

    [[local_server.kv_stores.yourdle]]
      file = "./setup/pops.json"
      key = "pops"

    [[local_server.kv_stores.yourdle-feedback]]
      file = "./setup/feedback.json"
      key = "1690380492-f283dbe6-306f-402a-af8c-1c3ad87b1db3"

    [[local_server.kv_stores.yourdle-stats]]
      file = "./setup/stats.json"
      key = "pops-1690380492-f283dbe6-306f-402a-af8c-1c3ad87b1db3"
